---
# front-end
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app_name }}-web-{{ .Values.environmentName }}"
  namespace: formbuilder-saas-{{ .Values.environmentName }}
spec:
  replicas: {{ .Values.replicas.web }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.web.maxSurge }}
      maxUnavailable: {{ .Values.strategy.web.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{ .Values.app_name }}-web-{{ .Values.environmentName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app_name }}-web-{{ .Values.environmentName }}"
        appGroup: "fb-editor"
        fb-service-token-cache-access: "true"
        tier: "frontend"
    spec:
      containers:
      - name: "{{ .Values.app_name }}-web-{{ .Values.environmentName }}"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-editor-web:{{ .Values.circleSha1 }}"
        {{- if ((.Values.resources).requests) }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        {{- end }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp-files
        securityContext:
          runAsUser: 1001
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep", "10"]
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: {{ .Values.livenessProbe.web.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.web.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.web.successThreshold }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: {{ .Values.readinessProbe.web.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.web.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.web.successThreshold }}
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: "{{ .Values.app_name }}-config-map"
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: auth0_client_id
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: auth0_client_secret
          - name: ENCODED_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encoded_private_key
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encryption_key
          - name: ENCRYPTION_SALT
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encryption_salt
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-formbuilder-editor-{{ .Values.environmentName }}
                key: url
          - name: EDITOR_SERVICE_ACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.bearer_token }}
                key: token
          - name: SUBMISSION_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: submission_encryption_key
          - name: SERVICE_SENTRY_DSN_TEST
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_dsn_test
          - name: SERVICE_SENTRY_DSN_LIVE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_dsn_live
          - name: SERVICE_SENTRY_CSP_URL_TEST
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_csp_url_test
          - name: SERVICE_SENTRY_CSP_URL_LIVE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_csp_url_live
          - name: SLACK_PUBLISH_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: slack_publish_webhook
          - name: PINGDOM_TOKEN
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: pingdom_token
          - name: PINGDOM_ALERT_INTEGRATION_ID
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: pingdom_alert_integration_id
          - name: AWS_SES_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: aws_ses_secret_access_key
          - name: AWS_SES_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: aws_ses_access_key_id
      volumes:
        - name: tmp-files
          emptyDir: {}
---
# workers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app_name }}-workers-{{ .Values.environmentName }}"
  namespace: formbuilder-saas-{{ .Values.environmentName }}
spec:
  replicas: {{ .Values.replicas.workers }}
  selector:
    matchLabels:
      app: "{{ .Values.app_name }}-workers-{{ .Values.environmentName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app_name }}-workers-{{ .Values.environmentName }}"
        appGroup: "fb-editor"
        fb-service-token-cache-access: "true"
        tier: "frontend"
    spec:
      securityContext:
        runAsUser: 1001
      serviceAccountName: "formbuilder-editor-workers-{{ .Values.environmentName }}"
      containers:
      - name: "{{ .Values.app_name }}-workers-{{ .Values.environmentName }}"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-editor-workers:{{ .Values.circleSha1 }}"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-files
        securityContext:
          runAsUser: 1001
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep", "10"]
        ports:
          - containerPort: 3000
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: "{{ .Values.app_name }}-config-map"
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: auth0_client_id
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: auth0_client_secret
          - name: ENCODED_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encoded_private_key
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encryption_key
          - name: ENCRYPTION_SALT
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encryption_salt
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-formbuilder-editor-{{ .Values.environmentName }}
                key: url
          - name: EDITOR_SERVICE_ACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.bearer_token }}
                key: token
          - name: SUBMISSION_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: submission_encryption_key
          - name: SERVICE_SENTRY_DSN_TEST
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_dsn_test
          - name: SERVICE_SENTRY_DSN_LIVE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_dsn_live
          - name: SERVICE_SENTRY_CSP_URL_TEST
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_csp_url_test
          - name: SERVICE_SENTRY_CSP_URL_LIVE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_csp_url_live
          - name: SLACK_PUBLISH_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: slack_publish_webhook
          - name: AWS_S3_ACCESS_KEY_ID_DEV
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: aws_s3_access_key_id_dev
          - name: AWS_S3_SECRET_ACCESS_KEY_DEV
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: aws_s3_secret_access_key_dev
          - name: AWS_S3_BUCKET_DEV
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: aws_s3_bucket_dev
          - name: AWS_S3_ACCESS_KEY_ID_PRODUCTION
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: aws_s3_access_key_id_production
          - name: AWS_S3_SECRET_ACCESS_KEY_PRODUCTION
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: aws_s3_secret_access_key_production
          - name: AWS_S3_BUCKET_PRODUCTION
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: aws_s3_bucket_production
      volumes:
        - name: tmp-files
          emptyDir: {}
