apiVersion: v1
kind: Secret
metadata:
  name: fb-editor-secrets-{{ .Values.environmentName }}
  namespace: formbuilder-saas-{{ .Values.environmentName }}
type: Opaque
data:
  secret_key_base: {{ .Values.secret_key_base }}
  sentry_dsn: {{ .Values.sentry_dsn }}
  auth0_client_id: {{ .Values.auth0_client_id }}
  auth0_client_secret: {{ .Values.auth0_client_secret }}
  encoded_private_key: {{ .Values.encoded_private_key}}
  encryption_key: {{ .Values.encryption_key }}
  encryption_salt: {{ .Values.encryption_salt }}
  submission_encryption_key: {{ .Values.submission_encryption_key }}
  service_sentry_dsn_test: {{ .Values.service_sentry_dsn_test }}
  service_sentry_dsn_live: {{ .Values.service_sentry_dsn_live }}
  service_sentry_csp_url_test: {{ .Values.service_sentry_csp_url_test }}
  service_sentry_csp_url_live: {{ .Values.service_sentry_csp_url_live }}
  slack_publish_webhook: {{ .Values.slack_publish_webhook }}
  pingdom_token: {{ .Values.pingdom_token }}
  pingdom_alert_integration_id: {{ .Values.pingdom_alert_integration_id }}
  aws_ses_access_key_id: {{ .Values.aws_ses_access_key_id }}
  aws_ses_secret_access_key: {{ .Values.aws_ses_secret_access_key }}
  aws_s3_bucket_dev: {{ .Values.aws_s3_bucket_dev }}
  aws_s3_access_key_id_dev: {{ .Values.aws_s3_access_key_id_dev }}
  aws_s3_secret_access_key_dev: {{ .Values.aws_s3_secret_access_key_dev }}
  aws_s3_bucket_production: {{ .Values.aws_s3_bucket_production }}
  aws_s3_access_key_id_production: {{ .Values.aws_s3_access_key_id_production }}
  aws_s3_secret_access_key_production: {{ .Values.aws_s3_secret_access_key_production }}
