openapi: 3.0.2
info:
  version: 1.0.0
  title: Editor API Docs
  contact:
    email: form-builder-developers@digital.justice.gov.uk
  x-logo:
    url: 'https://raw.githubusercontent.com/ministryofjustice/fb-editor-console-electron/63a0d9a4cda23f361a1d52aa7af9400db29621ee/assets/images/govuk-crown.png'
  description: >
    # Introduction

    >
      This is the Editor API documentation.

    >
      The application is responsible for serving default text for all the services
    created by the MoJ Online Form Builder tool.

    >
      The code repository [can be found here](https://github.com/ministryofjustice/fb-editor).

    >
      In order to interact with the API each request must have a JWT bearer token in the Authorizaion
    header signed by a private key.
paths:
  /api/services/{service_id}/pages/{page_uuid}:
    $ref: 'paths/api@services@{service_id}@pages@{pages_uuid}.yaml'
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
