RSpec.describe EmailService::TransferRawMessage do
  subject(:message) do
    described_class.new(
      from: 'MoJ Forms <no-reply-moj-forms@digital.justice.gov.uk>',
      to: 'new_owner@example.com',
      previous_owner: 'previous_owner@example.com',
      service_name: 'The best form'
    )
  end

  let(:expected_email) do
    <<~RAW_MESSAGE
      From: MoJ Forms <no-reply-moj-forms@digital.justice.gov.uk>
      To: new_owner@example.com
      Subject: An MoJ Forms form has been transferred to you
      Content-Type: multipart/mixed; boundary="NextPart"

      --NextPart
      Content-Type: multipart/alternative; boundary="AltPart"

      --AltPart
      Content-Type: text/html; charset=utf-8
      Content-Transfer-Encoding: base64

      PGh0bWw+CiAgPGJvZHkgc3R5bGU9ImZvbnQtZmFtaWx5OiBIZWx2ZXRpY2Es
      IEFyaWFsLCBzYW5zLXNlcmlmO2ZvbnQtc2l6ZTogMTZweDttYXJnaW46IDA7
      Y29sb3I6IzBiMGMwYzsiPgoKICAgIDwhLS0gZ292dWsgYmFubmVyIC0tPgog
      ICAgPHRhYmxlIHJvbGU9InByZXNlbnRhdGlvbiIgd2lkdGg9IjEwMCUiIHN0
      eWxlPSJib3JkZXItY29sbGFwc2U6IGNvbGxhcHNlO21pbi13aWR0aDogMTAw
      JTt3aWR0aDogMTAwJSAhaW1wb3J0YW50OyIgY2VsbHBhZGRpbmc9IjAiIGNl
      bGxzcGFjaW5nPSIwIiBib3JkZXI9IjAiPgogICAgICAgIDx0cj4KICAgICAg
      ICAgICAgPHRkIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjUzIiBiZ2NvbG9yPSIj
      MGIwYzBjIj4KICAgICAgICAgICAgICAgIDwhLS1baWYgKGd0ZSBtc28gOSl8
      KElFKV0+CiAgICAgICAgICAgICAgICAgICAgPHRhYmxlIHJvbGU9InByZXNl
      bnRhdGlvbiIgd2lkdGg9IjU4MCIgYWxpZ249ImNlbnRlciIgY2VsbHBhZGRp
      bmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBib3JkZXI9IjAiIHN0eWxlPSJib3Jk
      ZXItY29sbGFwc2U6IGNvbGxhcHNlO3dpZHRoOiA1ODBweDsiPgogICAgICAg
      ICAgICAgICAgICAgIDx0cj4KICAgICAgICAgICAgICAgICAgICA8dGQ+CiAg
      ICAgICAgICAgICAgICA8IVtlbmRpZl0tLT4KICAgICAgICAgICAgICAgIDx0
      YWJsZSByb2xlPSJwcmVzZW50YXRpb24iIHdpZHRoPSIxMDAlIiBzdHlsZT0i
      Ym9yZGVyLWNvbGxhcHNlOiBjb2xsYXBzZTttYXgtd2lkdGg6IDU4MHB4OyIg
      Y2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBib3JkZXI9IjAiIGFs
      aWduPSJjZW50ZXIiPgogICAgICAgICAgICAgICAgICAgIDx0cj4KICAgICAg
      ICAgICAgICAgICAgICAgICAgPHRkIHdpZHRoPSI3MCIgYmdjb2xvcj0iIzBi
      MGMwYyIgdmFsaWduPSJtaWRkbGUiPgogICAgICAgICAgICAgICAgICAgICAg
      ICAgICAgPHRhYmxlIHJvbGU9InByZXNlbnRhdGlvbiIgY2VsbHBhZGRpbmc9
      IjAiIGNlbGxzcGFjaW5nPSIwIiBib3JkZXI9IjAiIHN0eWxlPSJib3JkZXIt
      Y29sbGFwc2U6IGNvbGxhcHNlOyI+CiAgICAgICAgICAgICAgICAgICAgICAg
      ICAgICAgICAgPHRyPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
      ICAgICA8dGQgc3R5bGU9InBhZGRpbmctbGVmdDogMTBweCI+CiAgICAgICAg
      ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aW1nCiAgICAgICAg
      ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHNyYz0iaHR0cHM6
      Ly9zdGF0aWMubm90aWZpY2F0aW9ucy5zZXJ2aWNlLmdvdi51ay9pbWFnZXMv
      Z292dWstbG9nb3R5cGUtdHVkb3ItY3Jvd24ucG5nIgogICAgICAgICAgICAg
      ICAgICAgICAgICAgICAgICAgICAgICAgICAgICBhbHQ9IiIKICAgICAgICAg
      ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgaGVpZ2h0PSIzMiIK
      ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYm9y
      ZGVyPSIwIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
      ICAgICBzdHlsZT0iTWFyZ2luLXRvcDogMnB4OyIKICAgICAgICAgICAgICAg
      ICAgICAgICAgICAgICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgICAg
      ICAgICAgICAgICAgICAgICAgPC90ZD4KICAgICAgICAgICAgICAgICAgICAg
      ICAgICAgICAgICAgICAgPHRkIHN0eWxlPSJmb250LXNpemU6IDI4cHg7IGxp
      bmUtaGVpZ2h0OiAxLjMxNTc4OTQ3NDsgTWFyZ2luLXRvcDogNHB4OyBwYWRk
      aW5nLWxlZnQ6IDEwcHg7Ij4KICAgICAgICAgICAgICAgICAgICAgICAgICAg
      ICAgICAgICAgICAgIDxzcGFuIHN0eWxlPSIKICAgICAgICAgICAgICAgICAg
      ICAgICAgICAgICAgICAgICAgICAgIGZvbnQtZmFtaWx5OiBIZWx2ZXRpY2Es
      IEFyaWFsLCBzYW5zLXNlcmlmOwogICAgICAgICAgICAgICAgICAgICAgICAg
      ICAgICAgICAgICAgICAgZm9udC13ZWlnaHQ6IDcwMDsKICAgICAgICAgICAg
      ICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNvbG9yOiAjZmZmZmZmOwog
      ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdGV4dC1k
      ZWNvcmF0aW9uOiBub25lOwogICAgICAgICAgICAgICAgICAgICAgICAgICAg
      ICAgICAgICAgICAgdmVydGljYWwtYWxpZ246dG9wOwogICAgICAgICAgICAg
      ICAgICAgICAgICAgICAgICAgICAgICAgICAgZGlzcGxheTogaW5saW5lLWJs
      b2NrOwogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
      Ij5UaGUgYmVzdCBmb3JtPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAg
      ICAgICAgICAgICAgICA8L3RkPgogICAgICAgICAgICAgICAgICAgICAgICAg
      ICAgICAgIDwvdHI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3Rh
      YmxlPgogICAgICAgICAgICAgICAgICAgICAgICA8L3RkPgogICAgICAgICAg
      ICAgICAgICAgIDwvdHI+CiAgICAgICAgICAgICAgICA8L3RhYmxlPgogICAg
      ICAgICAgICAgICAgPCEtLVtpZiAoZ3RlIG1zbyA5KXwoSUUpXT4KICAgICAg
      ICAgICAgICAgICAgICA8L3RkPgogICAgICAgICAgICAgICAgICAgIDwvdHI+
      CiAgICAgICAgICAgICAgICAgICAgPC90YWJsZT4KICAgICAgICAgICAgICAg
      IDwhW2VuZGlmXS0tPgogICAgICAgICAgICA8L3RkPgogICAgICAgIDwvdHI+
      CiAgICA8L3RhYmxlPgogICAgPHRhYmxlCiAgICAgICAgcm9sZT0icHJlc2Vu
      dGF0aW9uIgogICAgICAgIGNsYXNzPSJjb250ZW50IgogICAgICAgIGFsaWdu
      PSJjZW50ZXIiCiAgICAgICAgY2VsbHBhZGRpbmc9IjAiCiAgICAgICAgY2Vs
      bHNwYWNpbmc9IjAiCiAgICAgICAgYm9yZGVyPSIwIgogICAgICAgIHN0eWxl
      PSJib3JkZXItY29sbGFwc2U6IGNvbGxhcHNlO21heC13aWR0aDogNTgwcHg7
      IHdpZHRoOiAxMDAlICFpbXBvcnRhbnQ7IgogICAgICAgIHdpZHRoPSIxMDAl
      IgogICAgICAgID4KICAgICAgICA8dHI+CiAgICAgICAgICAgIDx0ZCB3aWR0
      aD0iMTAiIGhlaWdodD0iMTAiIHZhbGlnbj0ibWlkZGxlIj48L3RkPgogICAg
      ICAgICAgICA8dGQ+CiAgICAgICAgICAgICAgICA8IS0tW2lmIChndGUgbXNv
      IDkpfChJRSldPgogICAgICAgICAgICAgICAgICAgIDx0YWJsZSByb2xlPSJw
      cmVzZW50YXRpb24iIHdpZHRoPSI1NjAiIGFsaWduPSJjZW50ZXIiIGNlbGxw
      YWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgYm9yZGVyPSIwIiBzdHlsZT0i
      Ym9yZGVyLWNvbGxhcHNlOiBjb2xsYXBzZTt3aWR0aDogNTYwcHg7Ij4KICAg
      ICAgICAgICAgICAgICAgICA8dHI+CiAgICAgICAgICAgICAgICAgICAgPHRk
      IGhlaWdodD0iMTAiPgogICAgICAgICAgICAgICAgPCFbZW5kaWZdLS0+CiAg
      ICAgICAgICAgICAgICA8dGFibGUgcm9sZT0icHJlc2VudGF0aW9uIiB3aWR0
      aD0iMTAwJSIgY2VsbHBhZGRpbmc9IjAiIGNlbGxzcGFjaW5nPSIwIiBib3Jk
      ZXI9IjAiIHN0eWxlPSJib3JkZXItY29sbGFwc2U6IGNvbGxhcHNlOyI+CiAg
      ICAgICAgICAgICAgICAgICAgPHRyPgogICAgICAgICAgICAgICAgICAgICAg
      ICA8dGQgYmdjb2xvcj0iIzFENzBCOCIgd2lkdGg9IjEwMCUiIGhlaWdodD0i
      MTAiPjwvdGQ+CiAgICAgICAgICAgICAgICAgICAgPC90cj4KICAgICAgICAg
      ICAgICAgIDwvdGFibGU+CiAgICAgICAgICAgICAgICA8IS0tW2lmIChndGUg
      bXNvIDkpfChJRSldPgogICAgICAgICAgICAgICAgICAgIDwvdGQ+CiAgICAg
      ICAgICAgICAgICAgICAgPC90cj4KICAgICAgICAgICAgICAgICAgICA8L3Rh
      YmxlPgogICAgICAgICAgICAgICAgPCFbZW5kaWZdLS0+CiAgICAgICAgICAg
      IDwvdGQ+CiAgICAgICAgICAgIDx0ZCB3aWR0aD0iMTAiIHZhbGlnbj0ibWlk
      ZGxlIiBoZWlnaHQ9IjEwIj48L3RkPgogICAgICAgIDwvdHI+CiAgICA8L3Rh
      YmxlPgogICAgPCEtLSBlbmQgZ292dWsgYmFubmVyIC0tPgoKICAgIDx0YWJs
      ZQogICAgICAgIHJvbGU9InByZXNlbnRhdGlvbiIKICAgICAgICBjbGFzcz0i
      Y29udGVudCIKICAgICAgICBhbGlnbj0iY2VudGVyIgogICAgICAgIGNlbGxw
      YWRkaW5nPSIwIgogICAgICAgIGNlbGxzcGFjaW5nPSIwIgogICAgICAgIGJv
      cmRlcj0iMCIKICAgICAgICBzdHlsZT0iYm9yZGVyLWNvbGxhcHNlOiBjb2xs
      YXBzZTttYXgtd2lkdGg6IDU4MHB4OyB3aWR0aDogMTAwJSAhaW1wb3J0YW50
      OyIKICAgICAgICB3aWR0aD0iMTAwJSIKICAgICAgICA+CiAgICAgICAgPHRy
      PgogICAgICAgICAgICA8dGQgd2lkdGg9IjEwIiB2YWxpZ249Im1pZGRsZSI+
      PGJyIC8+PC90ZD4KICAgICAgICAgICAgPHRkIHN0eWxlPSJmb250LWZhbWls
      eTogSGVsdmV0aWNhLCBBcmlhbCwgc2Fucy1zZXJpZjsgZm9udC1zaXplOiAx
      OXB4OyBsaW5lLWhlaWdodDogMS4zMTU3ODk0NzQ7IG1heC13aWR0aDogNTYw
      cHg7Ij4KICAgICAgICAgICAgICAgIDwhLS1baWYgKGd0ZSBtc28gOSl8KElF
      KV0+CiAgICAgICAgICAgICAgICAgICAgPHRhYmxlIHJvbGU9InByZXNlbnRh
      dGlvbiIgd2lkdGg9IjU2MCIgYWxpZ249ImNlbnRlciIgY2VsbHBhZGRpbmc9
      IjAiIGNlbGxzcGFjaW5nPSIwIiBib3JkZXI9IjAiIHN0eWxlPSJib3JkZXIt
      Y29sbGFwc2U6IGNvbGxhcHNlO3dpZHRoOiA1NjBweDsiPgogICAgICAgICAg
      ICAgICAgICAgIDx0cj4KICAgICAgICAgICAgICAgICAgICA8dGQgc3R5bGU9
      ImZvbnQtZmFtaWx5OiBIZWx2ZXRpY2EsIEFyaWFsLCBzYW5zLXNlcmlmOyBm
      b250LXNpemU6IDE5cHg7IGxpbmUtaGVpZ2h0OiAxLjMxNTc4OTQ3NDsiPgog
      ICAgICAgICAgICAgICAgPCFbZW5kaWZdLS0+CgogICAgICAgICAgICAgICAg
      VGhlIGZvbGxvd2luZyBmb3JtIGhhcyBiZWVuIHRyYW5zZmVycmVkIHRvIHlv
      dToKPGJyPjxicj5UaGUgYmVzdCBmb3JtPGJyPjxicj5Zb3UgYXJlIG5vdyBh
      YmxlIHRvIGFjY2VzcywgZWRpdCBhbmQgcHVibGlzaCB0aGlzIGZvcm0uIEl0
      IHdpbGwgYmUgbGlzdGVkIG9uIHRoZSDigJhZb3VyIGZvcm1z4oCZIHBhZ2Ug
      d2hlbiB5b3UgbmV4dCBzaWduIGluIHRvIE1vSiBGb3Jtcy4KPGJyPjxicj48
      YSBjbGFzcz0iZ292dWstbGluayIgaHJlZj0iaHR0cHM6Ly9tb2otZm9ybXMt
      ZWRpdG9yLnNlcnZpY2UuanVzdGljZS5nb3YudWsvIiB0YXJnZXQ9Il9ibGFu
      ayIgcmVsPSJub29wZW5lciBub3JlZmVycmVyIj5TaWduIGluIHRvIE1vSiBG
      b3JtczwvYT4KPGJyPjxicj5UaGlzIGNoYW5nZSB3YXMgcmVxdWVzdGVkIGJ5
      IHByZXZpb3VzX293bmVyQGV4YW1wbGUuY29tLgo8YnI+PGJyPklmIHlvdSBo
      YXZlIGFueSBxdWVzdGlvbnMsIHBsZWFzZSA8YSBjbGFzcz0iZ292dWstbGlu
      ayIgaHJlZj0iaHR0cHM6Ly9tb2otZm9ybXMuc2VydmljZS5qdXN0aWNlLmdv
      di51ay9jb250YWN0LyIgdGFyZ2V0PSJfYmxhbmsiIHJlbD0ibm9vcGVuZXIg
      bm9yZWZlcnJlciI+Y29udGFjdCB1czwvYT4uCgoKICAgICAgICAgICAgICAg
      IDwhLS1baWYgKGd0ZSBtc28gOSl8KElFKV0+CiAgICAgICAgICAgICAgICAg
      ICAgPC90ZD4KICAgICAgICAgICAgICAgICAgICA8L3RyPgogICAgICAgICAg
      ICAgICAgICAgIDwvdGFibGU+CiAgICAgICAgICAgICAgICA8IVtlbmRpZl0t
      LT4KICAgICAgICAgICAgPC90ZD4KICAgICAgICAgICAgPHRkIHdpZHRoPSIx
      MCIgdmFsaWduPSJtaWRkbGUiPjxiciAvPjwvdGQ+CiAgICAgICAgPC90cj4K
      ICAgICAgICA8dHI+CiAgICAgICAgICAgIDx0ZCBoZWlnaHQ9IjMwIj48YnIg
      Lz48L3RkPgogICAgICAgIDwvdHI+CiAgICA8L3RhYmxlPgogIDwvYm9keT4K
      PC9odG1sPgo=


      --NextPart--
    RAW_MESSAGE
  end

  it 'creates the expected raw message' do
    expect(message.to_s).to eq(expected_email)
  end
end
