feature_flags:
  developer_tools:
    local: true
    test: true   # formbuilder-saas-test
    live: false  # formbuilder-saas-live
  transfer_ownership:
    local: true
    test: true   # formbuilder-saas-test
    live: false  # formbuilder-saas-live
  first_time_publish_to_test_email:
    local: true
    test: true
    live: false
