feature_flags:
  developer_tools:
    local: true
    test: true   # formbuilder-saas-test
    live: false  # formbuilder-saas-live
  announcements:
    local: true
    test: true
    live: false
  transfer_ownership:
    local: true
    test: true   # formbuilder-saas-test
    live: false  # formbuilder-saas-live
