feature_flags:
  developer_tools:
    local: true
    test: true   # formbuilder-saas-test
    live: false  # formbuilder-saas-live
  address_component:
    local: true
    test: true
    live: false
