feature_flags:
  developer_tools:
    local: true
    test: true   # formbuilder-saas-test
    live: false  # formbuilder-saas-live
  transfer_ownership:
    local: true
    test: true   # formbuilder-saas-test
    live: false  # formbuilder-saas-live
