openapi: 3.0.2
info:
  version: 1.0.0
  title: Editor API Docs
  contact:
    email: form-builder-developers@digital.justice.gov.uk
  x-logo:
    url: >-
      https://raw.githubusercontent.com/ministryofjustice/fb-editor-console-electron/63a0d9a4cda23f361a1d52aa7af9400db29621ee/assets/images/govuk-crown.png
  description: |
    # Introduction
    >
      This is the Editor API documentation.

    >
      The application is responsible for serving default text for all the services
    created by the MoJ Online Form Builder tool.
    >
      The code repository [can be found here](https://github.com/ministryofjustice/fb-editor).

    >
      In order to interact with the API each request must have a JWT bearer token in the Authorizaion
    header signed by a private key.
paths:
  '/api/services/{service_id}/pages/{page_uuid}':
    get:
      tags:
        - Default Text
      summary: Get default text
      description: Gets the default text for a page
      operationId: default-text
      parameters:
        - name: service_id
          in: path
          description: The Service ID that needs to be updated
          required: true
          schema:
            type: string
        - name: page_uuid
          in: path
          description: The Page UUID
          required: true
          schema:
            type: string
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
        '403':
          description: Not authorised to perform operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        required: true
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    '200':
      type: object
      properties: null
      example:
        meta:
          default_text:
            section_heading: '[Optional section heading]'
            lede: '[Optional lede paragraph]'
            body: '[Optional content]'
            content: '[Optional content]'
            hint: '[Optional hint text]'
            option: Option
            option_hint: '[Optional hint text]'
    '403':
      type: object
      description: >-
        The error message returned when the requesting service does not have
        permission to perform the operation
      properties:
        message:
          description: Response message
          type: array
          items:
            type: string
            minLength: 1
            example: You do not have permission to perform this operation
      example:
        message: Unauthorised
security:
  - - basicAuth: []
